import React from "react";

const TermsOfUse =() =>{
  return (
    <section className="w-full bg-gray-50 py-20 px-4 md:px-16 lg:px-32 text-gray-800">
      <div className="max-w-5xl mx-auto">
        <h1 className="text-4xl font-bold mb-6 text-gray-900">Terms of Use</h1>
        <p className="text-lg leading-relaxed mb-6">
          This document is an electronic record in terms of the Information Technology Act, 2000 and
          rules thereunder as applicable and the amended provisions pertaining to electronic records
          in various statutes as amended by the Information Technology Act, 2000. This electronic
          record is generated by a computer system and does not require any physical or digital
          signatures.
        </p>

        <p className="text-lg leading-relaxed mb-6">
          This document is published in accordance with the provisions of Rule 3 (1) of the
          Information Technology (Intermediaries Guidelines) Rules, 2011 that require publishing the
          rules and regulations, privacy policy and Terms of Use for access or usage of the website.
          {/* The domain name <strong>www.adityavision.com</strong> (hereinafter referred to as the
          "Website") is owned by Aditya Vision Private Limited, a company incorporated under the
          Companies Act, 1956. */}
        </p>

        <p className="text-lg leading-relaxed mb-6">
          Your use of the Website, services, and tools are governed by the following terms and
          conditions ("Terms of Use") as applicable to the Website including applicable policies which
          are incorporated herein by reference. By mere use of the Website, You shall be contracting
          with Aditya Vision Private Limited and these terms and conditions constitute Your binding
          obligations with Aditya Vision.
        </p>

        <h2 className="text-2xl font-semibold mt-10 mb-4">User Agreement</h2>
        <p className="text-lg leading-relaxed mb-6">
          For the purpose of these Terms of Use, wherever the context so requires, "You" or "User"
          shall mean any natural or legal person who has agreed to become a buyer on the Website by
          providing Registration Data while registering as a Registered User. The terms "We",
          "Us", "Our" shall mean Aditya Vision Private Limited.
        </p>
        <p className="text-lg leading-relaxed mb-6">
          When You use any of the services provided by Us through the Website, including but not
          limited to reviews or feedback, You will be subject to the rules, guidelines, policies,
          terms, and conditions applicable to such service. We reserve the right to change, modify,
          add, or remove portions of these Terms of Use without prior written notice.
        </p>

        <h2 className="text-2xl font-semibold mt-10 mb-4">Your Account & Registration Obligations</h2>
        <p className="text-lg leading-relaxed mb-6">
          If You use the Website, You are responsible for maintaining the confidentiality of your
          Display Name and Password and for all activities that occur under your account. If You
          provide any information that is untrue, inaccurate, or not in accordance with these terms,
          We reserve the right to suspend or terminate your account.
        </p>
        <p className="text-lg leading-relaxed mb-6">
          Your mobile phone number and/or email address is treated as Your primary identifier on the
          Website. You agree to notify Us promptly if your registered contact information changes.
        </p>

        <h2 className="text-2xl font-semibold mt-10 mb-4">Communication</h2>
        <p className="text-lg leading-relaxed mb-6">
          When You use the Website or send emails or other data to Us, You agree that You are
          communicating with Us through electronic records and consent to receive communication via
          electronic means periodically.
        </p>
        <p className="text-lg leading-relaxed mb-6 italic border-l-4 pl-4 border-gray-400">
          "By submitting information with us, you agree to receive communication about products and
          services over SMS/RCS/WhatsApp/etc."
        </p>
      </div>
    </section>
  );
}

export default TermsOfUse;
